project_name: opd-go
# Output Go archives under artifacts/opd-go to avoid colliding with existing artifacts/*
dist: artifacts/opd-go

before:
  hooks:
    - go mod tidy

builds:
  - id: opd-go
    main: ./go/cmd/opd-go/main.go
    binary: opd-go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: archive
    builds:
      - opd-go
    format_overrides:
      - goos: windows
        format: zip
    # e.g. opd-go_v1.2.3_windows_amd64.zip
    name_template: "opd-go_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false

checksums:
  name_template: "opd-go_checksums.txt"

changelog:
  disable: true
