project_name: opd
# Output artifacts under ./artifacts
dist: artifacts

before:
  hooks:
    - go mod tidy

builds:
  - id: opd
    main: ./go/cmd/opd-go/main.go
    binary: opd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: binaries
    builds:
      - opd
    format: binary
    # Output names: opd-windows-x64.exe, opd-darwin-arm64, opd-linux-x64, etc.
    name_template: >-
      opd-{{ .Os }}-{{- if eq .Arch "amd64" -}}x64{{- else -}}{{ .Arch }}{{- end -}}{{ if eq .Os "windows" }}.exe{{ end }}
    wrap_in_directory: false

checksums:
  name_template: "opd_checksums.txt"

changelog:
  disable: true
