name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-docs"
  cancel-in-progress: false

jobs:
  deploy-docs:
    uses: ./.github/workflows/_reusable-gh-pages.yml
    with:
      app_path: apps/docs
