name: Docs Link Check (manual)

on:
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run docs link/anchor checker
        continue-on-error: true
        run: node scripts/docs-link-check.mjs
