name: opendeploy-provider-stub-smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  provider-stub-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build CLI
        run: pnpm -C packages/cli build

      - name: Create provider stub package
        run: |
          mkdir -p provider-stub
          cat > provider-stub/package.json << 'JSON'
          {
            "name": "@opendeploy/provider-stub",
            "version": "1.0.0",
            "type": "module",
            "main": "index.js"
          }
          JSON
          cat > provider-stub/index.js << 'JS'
          export const plugin = {
            setContext(ctx){ globalThis.__ctx = ctx },
            getCapabilities(){ return { name: 'Stub', supportsLocalBuild: false, supportsRemoteBuild: false, supportsStaticDeploy: true, supportsServerless: false, supportsLogsFollow: false, supportsAliasDomains: false, supportsRollback: false } },
            async validateAuth(){},
            async deployStatic({ cwd, outputDir, target }){ __ctx?.nd({ event: 'deploy:stub', target, outputDir }); return { ok: true, url: 'https://stub.example', logsUrl: 'https://stub.example/logs', final: true } }
          }
          export const id = 'stub'
          export const version = '1.0.0'
          export default { id, plugin, version }
          JS

      - name: Wire stub into node_modules
        run: |
          mkdir -p node_modules/@opendeploy
          cp -r provider-stub node_modules/@opendeploy/provider-stub

      - name: Run provider load smoke (NDJSON)
        env:
          OPD_NDJSON: '1'
        run: |
          node -e "(async()=>{const { loadProvider } = await import('./packages/cli/dist/core/provider-system/provider.js'); const p = await loadProvider('stub'); console.log(JSON.stringify({ ok: !!p, id: p.id, final:true })); })()"
