# GoReleaser config for opd-go sidecar binaries
# Builds portable binaries for Windows, Linux, and macOS and publishes
# archives named as: opd-go_<version>_<os>_<arch>.(tar.gz|zip)

version: 2

project_name: opd-go

before:
  hooks:
    - go mod tidy -C ./packages/cli/go

builds:
  - id: opd-go
    main: ./packages/cli/go/cmd/opd-go
    binary: opd-go
    env:
      - CGO_ENABLED=0
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]
    flags: ["-trimpath"]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    builds: [opd-go]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "opd-go_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums_{{ .Version }}.txt"

release:
  draft: false
  prerelease: auto

changelog:
  use: git
