name: "Reusable: Deploy App to Cloudflare Pages (Next on Pages)"

on:
  workflow_call:
    inputs:
      app_path:
        description: "Relative path to the app under repo root (e.g., apps/docs)"
        required: true
        type: string
      project_name:
        description: "Cloudflare Pages project name"
        required: true
        type: string

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_path }}
    env:
      DEPLOY_TARGET: cloudflare
      NEXT_PUBLIC_BASE_PATH: ''
      NEXT_IGNORE_BUILD_CACHE: '1'
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug runner
        run: |
          echo "Runner: $(uname -a)"
          echo "PWD=$(pwd)"
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.13.1 --activate

      - name: Debug versions
        run: |
          node -v
          pnpm -v

      - name: Approve native build scripts
        run: pnpm approve-builds @tailwindcss/oxide esbuild sharp workerd

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build with Next on Pages
        run: |
          rm -rf .vercel/output .next
          npx -y @cloudflare/next-on-pages@1

      - name: Upload .vercel output (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vercel-output
          path: ${{ inputs.app_path }}/.vercel/output
          if-no-files-found: warn

      - name: Deploy to Cloudflare Pages
        if: ${{ env.CF_API_TOKEN != '' && env.CF_ACCOUNT_ID != '' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          packageManager: npm
          command: pages deploy ${{ inputs.app_path }}/.vercel/output/static --project-name ${{ inputs.project_name }}

      - name: Skip deploy (missing Cloudflare secrets)
        if: ${{ env.CF_API_TOKEN == '' || env.CF_ACCOUNT_ID == '' }}
        run: |
          echo "Skipping Cloudflare deploy: missing CLOUDFLARE_API_TOKEN and/or CLOUDFLARE_ACCOUNT_ID repo secrets."
          echo "Build succeeded and .vercel/output/* was generated. Configure secrets and re-run to deploy."
