name: Docs & Netlify Guard

on:
  pull_request:
    branches: [ "**" ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if Netlify artifacts or legacy docs exist
        run: |
          set -euo pipefail
          FAIL=0
          check_exists() {
            if [ -e "$1" ]; then
              echo "Found forbidden path: $1" >&2
              FAIL=1
            fi
          }
          # Forbidden Netlify artifacts
          check_exists packages/cli/docs/providers/netlify.md
          check_exists packages/cli/schemas/examples/start.netlify.json
          check_exists packages/cli/schemas/examples/up.netlify.json
          check_exists packages/cli/scripts/smoke/netlify-direct.sh
          check_exists packages/cli/scripts/smoke/netlify-direct.ps1
          check_exists .netlify

          # Legacy docs locations (should be migrated to apps/docs)
          if [ -d packages/cli/docs ]; then
            echo "Legacy docs directory present: packages/cli/docs" >&2
            FAIL=1
          fi
          if [ -d docs ]; then
            echo "Legacy root docs directory present: docs/" >&2
            FAIL=1
          fi

          if [ "$FAIL" -ne 0 ]; then
            echo "Guard failed. Migrate docs to apps/docs/ and remove Netlify artifacts." >&2
            exit 1
          fi

      - name: Allow mentions of Netlify in supported docs (informational only)
        run: |
          # This job intentionally does nothing; mentions inside apps/docs are allowed for context like "Not supported".
          true
