name: Security - Gitleaks

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --redact --config-path .gitleaks.toml --report-path ./.artifacts/gitleaks.sarif --report-format sarif
      - name: Upload Gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: ./.artifacts/gitleaks.sarif
          if-no-files-found: ignore
