name: OpenDeploy Provider Smoke

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * *'

jobs:
  provider-smoke:
    name: Provider Smoke — detect + doctor
    runs-on: ubuntu-latest
    env:
      OPD_FORCE_CI: '1'
      OPD_PROVIDER_MODE: 'virtual'
      OPD_NDJSON: '1'
    strategy:
      fail-fast: false
      matrix:
        provider: [ vercel, cloudflare, github ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build CLI
        run: pnpm -C packages/cli build

      - name: Create tiny example app
        shell: bash
        run: |
          set -euo pipefail
          ROOT=$(pwd)
          case "${{ matrix.provider }}" in
            vercel)
              APP="$ROOT/example-vercel"
              mkdir -p "$APP"
              cat > "$APP/next.config.js" <<'EOF'
              /** Minimal Next config to trigger detect */
              module.exports = {
                reactStrictMode: true,
              }
              EOF
              ;;
            cloudflare)
              APP="$ROOT/example-cloudflare"
              mkdir -p "$APP"
              cat > "$APP/next.config.js" <<'EOF'
              /** Minimal Next config to trigger Cloudflare checks */
              module.exports = {
                reactStrictMode: true,
              }
              EOF
              cat > "$APP/wrangler.toml" <<'EOF'
              name = "example-next-on-pages"
              compatibility_date = "2024-01-01"
              EOF
              ;;
            github)
              APP="$ROOT/example-github"
              mkdir -p "$APP"
              cat > "$APP/next.config.js" <<'EOF'
              /** Simulate static export for GH Pages */
              module.exports = {
                output: 'export',
              }
              EOF
              mkdir -p "$APP/public"
              echo "hello" > "$APP/public/.nojekyll"
              ;;
          esac
          echo "APP_DIR=$APP" >> $GITHUB_ENV
          mkdir -p ./.artifacts

      - name: Detect (JSON)
        run: node packages/cli/dist/index.js detect --json --path "$APP_DIR" | tee ./.artifacts/detect-${{ matrix.provider }}.json

      - name: Doctor (JSON, non-strict)
        run: node packages/cli/dist/index.js doctor --json --path "$APP_DIR" | tee ./.artifacts/doctor-${{ matrix.provider }}.json

      - name: Upload provider smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-smoke-${{ matrix.provider }}
          path: ./.artifacts/**/*.json
          if-no-files-found: ignore
