name: Quickstart (GitHub Pages)

on:
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build OpenDeploy CLI
        run: pnpm --filter "./packages/cli" build

      - name: GitHub Pages preflight (no deploy)
        env:
          OPD_FORCE_CI: '1'
          OPD_NDJSON: '1'
          OPD_STRICT_PLUGIN_VERSION: '1'
          OPD_SCHEMA_STRICT: '1'
        run: |
          node packages/cli/dist/index.js up github \
            --preflight-only --strict-preflight \
            --json --summary-only

      # For actual deployment, prefer the generated reusable workflow:
      #   .github/workflows/deploy-app-gh-pages.yml (uses _reusable-gh-pages.yml)
      # Or use your existing Pages workflow.
