name: OpenDeploy Real E2E

on:
  workflow_dispatch:

jobs:
  vercel-preview-real:
    if: ${{ secrets.VERCEL_TOKEN && secrets.VERCEL_PROJECT_ID && secrets.VERCEL_ORG_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable corepack & install
        run: |
          corepack enable && corepack prepare pnpm@10.13.1 --activate
          pnpm install --no-frozen-lockfile
      - name: Approve native build scripts
        run: pnpm approve-builds @tailwindcss/oxide esbuild sharp workerd
      - name: Build CLI
        run: pnpm build
      - name: Scaffold Next.js app
        run: |
          npx create-next-app@latest smoke-next --ts --eslint --src-dir --app --tailwind --use-pnpm --no-git --import-alias @/*
          cd smoke-next
          pnpm build
      - name: Prepare artifacts dir
        run: mkdir -p ./.artifacts
      - name: Up vercel preview (real)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          node packages/cli/dist/index.js up vercel \
            --env preview \
            --project-id "${{ secrets.VERCEL_PROJECT_ID }}" \
            --org-id "${{ secrets.VERCEL_ORG_ID }}" \
            --json --ndjson --summary-only \
            --json-file ./.artifacts/vercel-up.json \
            --ndjson-file ./.artifacts/vercel-up.ndjson
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: real-vercel-preview-output
          path: ./.artifacts
          if-no-files-found: ignore

  netlify-preview-real:
    if: ${{ secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable corepack & install
        run: |
          corepack enable && corepack prepare pnpm@10.13.1 --activate
          pnpm install --no-frozen-lockfile
      - name: Build CLI
        run: pnpm build
      - name: Scaffold Astro app
        run: |
          npm create astro@latest -- --template basics --skip-install --git false --yes
          cd basics
          pnpm install
          pnpm build
      - name: Prepare artifacts dir
        run: mkdir -p ./.artifacts
      - name: Up netlify preview (real, no-build)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          node packages/cli/dist/index.js up netlify \
            --env preview \
            --project "${{ secrets.NETLIFY_SITE_ID }}" \
            --no-build \
            --json --ndjson --summary-only \
            --json-file ./.artifacts/netlify-up.json \
            --ndjson-file ./.artifacts/netlify-up.ndjson
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: real-netlify-preview-output
          path: ./.artifacts
          if-no-files-found: ignore
