name: Release (nested; manual only)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.13.1 --activate

      - name: Install deps (CLI)
        run: pnpm install --frozen-lockfile
        working-directory: "OpenDeploy CLI"

      - name: Build (CLI)
        run: pnpm build
        working-directory: "OpenDeploy CLI"

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp "OpenDeploy CLI/dist/index.js" artifacts/opd.js
          if command -v sha256sum >/dev/null 2>&1; then
            sha256sum artifacts/opd.js > artifacts/checksums.txt
          else
            shasum -a 256 artifacts/opd.js > artifacts/checksums.txt
          fi

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          artifacts: "artifacts/*"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "./OpenDeploy CLI"
          file: "./OpenDeploy CLI/Dockerfile"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/opd:latest
            ghcr.io/${{ github.repository_owner }}/opd:${{ github.ref_name }}
